# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Andrew Vleesch du Bois
# Description of the Site
description: Blog and Portfolio Site
# URL of Image of the Site
site-image: /MySite/assets/images/file_000000009e1c61fdb0710179329d9c53.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/6963944/pexels-photo-6963944.jpeg?_gl=1*1mg3ikw*_ga*MTIxMDQ2ODMyMy4xNzUzNTkyNjQ4*_ga_8JE65Q40S6*czE3NTM1OTI2NDckbzEkZzEkdDE3NTM1OTI4NDUkajEzJGwwJGgw.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: drew.vdb@protonmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: thedevslot
github_username:  ThunderByteCyber
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: ThunderByteCyber

# Name of the Author
author-name: ThunderByteCyber
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/ThunderByteCyber/MySite/refs/heads/master/images/Screenshot_20250310_051443_Outlook.jpg
# 60 Words About the Author
author-about: I am a high-achieving and motivated individual currently studying cybersecurity and digital forensics, with a strong desire to investigate cybercrime. I am passionate about problem-solving, critical thinking, and applying ethical practices in complex environments. My goal is to work as a digital forensic investigator, contributing to investigations that support law enforcement and national security. I value continuous learning, integrity, and collaboration, and I am committed to making a meaningful impact in the cybersecurity field through responsible and evidence-based practice.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ThunderByteCyber

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
